name: Deploy Dev CDK Stacks

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Lambda code
        run: npm run build

      - name: Create Lambda asset folders (if needed)
        run: |
          mkdir -p dist/lambdas/resolvers
          mkdir -p dist/lambdas/automation
          mkdir -p dist/lambdas/iot
          mkdir -p dist/lambdas/stripe
          echo "// placeholder" > dist/lambdas/resolvers/index.js
          echo "// placeholder" > dist/lambdas/automation/index.js
          echo "// placeholder" > dist/lambdas/iot/index.js
          echo "// placeholder" > dist/lambdas/stripe/index.js

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Dev CDK Stacks
        run: npx cdk deploy --all --require-approval never -c env=dev